version: "3"

#docker-compose.override.yml is loaded and merged with docker-compose.yml by default when calling docker-compose up.
#This file won't be merged when using docker-compose -f docker-compose.yml up (or using any other compose file).
services:
  mock-aws-rest-api:
    volumes:
      - ./lambda_functions/:/var/www/lambda_functions/
      - ./mock_integration_rest_api/:/var/www/mock_integration_rest_api/
