---
version: '3'

services:
  postgres:
    image: postgres
    ports:
      - "8765:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
  broker-app:
    image: pactfoundation/pact-broker
    ports:
      - "9897:80"
      - "9292:9292"
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      PACT_BROKER_DATABASE_USERNAME: postgres
      PACT_BROKER_DATABASE_PASSWORD: password
      PACT_BROKER_DATABASE_HOST: postgres
      PACT_BROKER_DATABASE_NAME: postgres
      # Uncomment these two options for debugging purposes:
      # PACT_BROKER_WEBHOOK_HOST_WHITELIST: circleci.com
      # PACT_BROKER_LOG_LEVEL: DEBUG
  mock-aws-rest-api:
    build:
      context: ./mock_integration_rest_api
      dockerfile: Dockerfile
    environment:
      MOCKING_ENV: mock-sirius
    volumes:
      - ./lambda_functions/:/var/www/lambda_functions/
      - ./mock_integration_rest_api/:/var/www/mock_integration_rest_api/
    ports:
      - "4343:4343"
  mock-sirius:
    build:
      context: ./mock_sirius_backend
      dockerfile: Dockerfile
    environment:
      - MOCKING_ENV
    volumes:
      - ./mock_sirius_backend/:/var/www/mock_sirius_backend/
    ports:
      - "5001:5001"
  check-pact-deployable:
    build:
      context: ./pact
      dockerfile: Dockerfile
      args:
        AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
        AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
        AWS_SESSION_TOKEN: $AWS_SESSION_TOKEN
