---
version: '3'

services:
  mock-aws-rest-api:
    build:
      context: ./mock_integration_rest_api
      dockerfile: Dockerfile-ci
    environment:
      MOCKING_ENV: mock-sirius
    volumes:
      - ./lambda_functions/:/var/www/lambda_functions/
      - ./mock_integration_rest_api/:/var/www/mock_integration_rest_api/
  mock-sirius:
    build:
      context: ./mock_sirius_backend
      dockerfile: Dockerfile-ci
    environment:
      - MOCKING_ENV
    volumes:
      - ./mock_sirius_backend/:/var/www/mock_sirius_backend/
  pact-verifier:
    build:
      context: ./pact_provider
      dockerfile: Dockerfile-ci
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
