ARG FUNCTION_DIR="/app/lambda_functions/v2"

# === BUILD IMAGE ===
FROM python:3.14.7-slim@sha256:51dafde81dbdb6ebde285137a295cf18a47ca95234fe388a343719cb97305b3d AS builder
# Include global arg in this stage of the build
ARG FUNCTION_DIR
# Set the working directory to /app
WORKDIR /app

# Install the runtime interface client
COPY --from=ghcr.io/astral-sh/uv@sha256:2bb3ebca0a796a155094a27773d290c4b074572e6107f171d88d086682fd2500 /uv /uvx /bin/
COPY requirements/uv.lock requirements/uv.lock
COPY requirements/pyproject.toml requirements/pyproject.toml
RUN cd /app/requirements && uv export --locked -o requirements.txt \
    && python -m pip install --no-cache-dir \
    --target /app \
    -r requirements.txt

COPY requirements-test/uv.lock requirements-test/uv.lock
COPY requirements-test/pyproject.toml requirements-test/pyproject.toml
RUN cd /app/requirements-test && uv export --locked -o requirements.txt \
    && python -m pip install --no-cache-dir \
    --target /app \
    -r requirements.txt

COPY functions ${FUNCTION_DIR}/functions
COPY tests ${FUNCTION_DIR}/tests
COPY test-app.sh /app/test-app.sh

# === FINAL IMAGE ===
FROM python:3.14.7-slim@sha256:51dafde81dbdb6ebde285137a295cf18a47ca95234fe388a343719cb97305b3d
# Include global arg in this stage of the build
ARG FUNCTION_DIR

WORKDIR /app

# Copy only the installed packages from the previous stage to the working directory
COPY --from=builder /app /app
ENV PYTHONPATH=/app
# Set the entrypoint for the unit tests
ENTRYPOINT ["/bin/sh", "test-app.sh"]
