swagger: '2.0'
info:
  version: 1.0.0
  title: Digideps Public API
  description: |
    Public API
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
basePath: /api/public/v1
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /csv:
    post:
      description: Upload CSV entrypoint
      parameters:
        - name: csv
          in: body
          description: Base64 encoded CSV to upload
          required: true
          schema:
            type: object
            properties:
              state:
                type: string
                pattern: '(.*?)'
                example: 'ZW1haWxfaWRlbnRpZmllcixvcmdhbmlzYXRpb25fbmFtZSwKZmFrZU9yZy5jby51aywsCmFub3RoZXJGYWtlT3JnLmNvbSxGQUtFIE9SRyBMTFAsCg=='
      responses:
        '201':
          description: State created
          schema:
            properties:
              result:
                type: string
                description: result
                pattern: '(.*?)'
                example: 'some result'
        '400':
          description: Invalid query
        '500':
          description: Unexpected error