# our base image
FROM python:3.6-slim

WORKDIR /var/www/
COPY requirements.txt .
RUN pip install -r requirements.txt
CMD mkdir mock_sirius_backend && chmod 755 mock_sirius_backend
WORKDIR /var/www/mock_sirius_backend/
COPY app.py .
COPY sirius_public_v1.yml .
WORKDIR /var/www/
ENV FLASK_APP=app.py
ENV FLASK_ENV=development

CMD ["python", "mock_sirius_backend/app.py"]
