#!/bin/bash
str="\- sigv4:"
latest_ver=$(ls -d ../lambda_functions/*/ | awk -F'/' '{print $3}' | grep '^v[1-9]\+' | sort -r | head -n1)
openapi_latest="deputy-reporting-openapi-${latest_ver}.yml"
openapi="deputy-reporting-openapi.yml"
cp ../"${openapi_latest}" ./"${openapi}"
echo "copied in.."
grep -n -B1 "${str}" ./"${openapi}" | sed -n 's/^\([0-9]\{1,\}\).*/\1d/p' > filelines.txt
sed -f filelines.txt "${openapi}" > "tmp_${openapi}"
mv "tmp_${openapi}" "${openapi}"
echo "security rows removed"
rm filelines.txt
