#!/bin/bash
str="x-amazon-apigateway-integration:"
latest_ver=$(ls -d lambda_functions/*/ | awk -F'/' '{print $2}' | sort -r | head -n1)
openapi_latest="deputy-reporting-openapi-${latest_ver}.yml"
openapi="deputy-reporting-openapi.yml"
cp ../$openapi ./$openapi
echo "copied in.."
grep -n -B2 $str ./$openapi | grep -v $str | sed -n 's/^\([0-9]\{1,\}\).*/\1d/p' > filelines.txt
sed -f filelines.txt $openapi > tmp_$openapi
mv tmp_$openapi $openapi
echo "security rows removed"
rm filelines.txt
