on:
  workflow_call:
    inputs:
      tag:
        description: 'Tag for docker image'
        required: true
        type: string
      build_identifier:
        description: 'Branch we are on'
        required: true
        type: string
    secrets:
      snyk_token:
        required: true

jobs:
  docker_build_scan_push:
    name: Build, Scan and Push Lambdas
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: "deputy-reporting-lambda"
            path: "lambda_functions/v2"
            scan_id: "deputy-reporting-lambda-scan"
          - name: "deputy-reporting-mock-sirius"
            path: "mock_sirius"
            scan_id: "deputy-reporting-mock-sirius-scan"

    steps:
      - name: Check out code
        id: checkout_code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Show build tag
        env:
          IMAGE_TAG: ${{ inputs.tag }}
        run: echo "Tag to use - ${IMAGE_TAG}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

      - name: Build Container
        id: build_container
        run: |
         docker buildx build \
            --platform linux/amd64 \
            --tag ${{ matrix.name }}:latest \
            --load \
            ${{ matrix.path }}

      - name: Run Snyk Scan
        id: snyk_scan
        uses: ministryofjustice/opg-github-actions/actions/snyk-scan@821b6f92327f0f195276860676aa8133d63f39dd # v4.5.1
        with:
          SNYK_TEST_IMAGE: ${{ matrix.name }}:latest
          SNYK_TOKEN: ${{ secrets.snyk_token }}
          snyk_test_args: "--severity-threshold=high"
          sarif_filepath: ./test-results
          sarif_filename: snyk-results.sarif
          snyk_policy_path: ${{ github.workspace }}/.github/.snyk

      - name: Upload SNYK scan results to GitHub Security tab
        if: steps.snyk_scan.outcome == 'success' && hashFiles('snyk-results.sarif') != ''
        uses: github/codeql-action/upload-sarif@9e907b5e64f6b83e7804b09294d44122997950d6 # v4.32.3
        with:
          sarif_file: test-results/snyk-results.sarif
          category: ${{ matrix.scan_id }}

      - uses: unfor19/install-aws-cli-action@f5b46b7f32cf5e7ebd652656c5036bf83dd1e60c # 1.0.8

      - name: configure OIDC AWS credentials for ECR push
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          role-to-assume: arn:aws:iam::311462405659:role/data-deputy-reporting-gh-actions-ecr-push
          role-session-name: deputy-reporting-github-actions-ecr-push
          role-duration-seconds: 900
          aws-region: eu-west-1

      - uses: aws-actions/amazon-ecr-login@261fc3d4806db1fa66a15cc11113c456db8870a7 # v2.1.0
        id: login_ecr
        with:
          registries: 311462405659
          mask-password: "true"

      - name: Push Container
        env:
          ECR_REGISTRY: ${{ steps.login_ecr.outputs.registry }}
          ECR_REPOSITORY: integrations
          IMAGE_NAME: ${{ matrix.name }}
          BUILD_IDENTIFIER: ${{ inputs.build_identifier }}
          IMAGE_TAG: ${{ inputs.tag }}
        run: |
          docker tag $IMAGE_NAME:latest $ECR_REGISTRY/$ECR_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG
          if [[ "${BUILD_IDENTIFIER}" == "main" ]]; then
            docker tag $IMAGE_NAME:latest $ECR_REGISTRY/$ECR_REPOSITORY/$IMAGE_NAME:latest
            docker tag $IMAGE_NAME:latest $ECR_REGISTRY/$ECR_REPOSITORY/$IMAGE_NAME:main-$IMAGE_TAG
          fi
          docker push --all-tags $ECR_REGISTRY/$ECR_REPOSITORY/$IMAGE_NAME
