on:
  workflow_call:
    inputs:
      environment_prefix:
        description: 'The environment prefix'
        required: true
        type: string
      sirius_account:
        description: 'Sirius account ID to use'
        required: true
        type: string
      digideps_account:
        description: 'Digideps account ID to use'
        required: true
        type: string
      role:
        description: 'The role suffix to use (example: operator)'
        required: true
        type: string
    secrets:
      aws_access_key_id_actions:
        required: true
      aws_secret_access_key_actions:
        required: true

jobs:
  health_check:
    name: Run health check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        id: checkout_code
        uses: actions/checkout@9a9194f87191a7e9055e3e9b95b8cfb13023bb08

      - name: Configure AWS Credentials For Health Check
        uses: aws-actions/configure-aws-credentials@ead1e6af28a20f26cc47437fa7e4c8357409ef24
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id_actions }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key_actions }}
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::${{ inputs.sirius_account }}:role/integrations-ci
          role-duration-seconds: 900
          role-session-name: OPGDeputyReportingGithubAction

      - name: Run the healthcheck test
        id: build_container
        run: go test
        working-directory: ./scripts/smoke
        env:
          ENVIRONMENT_PREFIX: ${{ inputs.environment_prefix }}
          ACCOUNT: ${{ inputs.digideps_account }}
          ROLE: ${{ inputs.role }}
