on:
  workflow_call:
    inputs:
      environment_prefix:
        description: 'The environment prefix'
        required: true
        type: string
      sirius_account:
        description: 'Sirius account ID to use'
        required: true
        type: string
      sirius_account_name:
        description: 'Sirius account name to use'
        required: true
        type: string
      digideps_account:
        description: 'Digideps account ID to use'
        required: true
        type: string
      role:
        description: 'The role suffix to use (example: operator)'
        required: true
        type: string

jobs:
  health_check:
    name: Run health check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        id: checkout_code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Configure AWS OIDC Credentials For Health Check
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          aws-region: eu-west-1
          role-to-assume: "arn:aws:iam::631181914621:role/oidc-data-deputy-reporting-${{ inputs.sirius_account_name }}"
          role-duration-seconds: 900
          role-session-name: OPGDeputyReportingGithubAction

      - name: Run the healthcheck test
        id: build_container
        run: go test
        working-directory: ./scripts/smoke
        env:
          ENVIRONMENT_PREFIX: ${{ inputs.environment_prefix }}
          BASE_ROLE: "integrations-ci"
          SIRIUS_ACCOUNT: ${{ inputs.sirius_account }}
          FINAL_ROLE: ${{ inputs.role }}
          DIGIDEPS_ACCOUNT: ${{ inputs.digideps_account }}
