on:
  workflow_call:
    inputs:
      lambda_names:
        description: 'The name of the lambda Docker container'
        required: true
        type: string
      tag:
        description: 'Tag for docker image'
        required: true
        type: string
      branch_name:
        description: 'Branch we are on'
        required: true
        type: string
    secrets:
      aws_access_key_id_actions:
        required: true
      aws_secret_access_key_actions:
        required: true

jobs:
  docker_build_scan_push:
    name: Build, Scan and Push Lambdas
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lambda_name: ${{ fromJSON(inputs.lambda_names) }}
    steps:
      - name: Check out code
        id: checkout_code
        uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222

      - name: Build Container
        id: build_container
        run: docker build --file ${{ matrix.lambda_name.path }}/Dockerfile --tag ${{ matrix.lambda_name.name }}:latest ${{ matrix.lambda_name.path }}

      - name: Trivy Image Vulnerability Scanner
        id: trivy_scan
        uses: aquasecurity/trivy-action@0.5.0
        with:
          image-ref: ${{ matrix.lambda_name.name }}:latest
          severity: 'HIGH,CRITICAL'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        id: trivy_upload_sarif
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

      - uses: unfor19/install-aws-cli-action@457b7980b125044247e455d87b9a26fc2299b787
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@86df881b31470c87bf594fc74e03243c2f43d0ff
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id_actions }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key_actions }}
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::311462405659:role/integrations-ci
          role-duration-seconds: 900
          role-session-name: OPGDeputyReportingGithubAction
      - name: Login to ECR
        id: login_ecr
        uses: aws-actions/amazon-ecr-login@v1.4.0
        with:
          registries: 311462405659
      - name: Push Container
        env:
          ECR_REGISTRY: ${{ steps.login_ecr.outputs.registry }}
          ECR_REPOSITORY: integrations/${{ matrix.lambda_name.name }}
          BRANCH_NAME: ${{ inputs.branch_name }}
        run: |
          docker tag ${{ matrix.lambda_name.name }}:latest $ECR_REGISTRY/$ECR_REPOSITORY:${{ inputs.tag }}
          if [ $BRANCH_NAME == "main" ]; then
            docker tag ${{ matrix.lambda_name.name }}:latest $ECR_REGISTRY/$ECR_REPOSITORY:latest
            docker tag ${{ matrix.lambda_name.name }}:latest $ECR_REGISTRY/$ECR_REPOSITORY:main-${{ inputs.tag }}
          fi
            docker push --all-tags $ECR_REGISTRY/$ECR_REPOSITORY
