name: "[Workflow] Path to Live"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}

on:
  push:
    branches:
      - main

permissions:
  actions: read
  checks: read
  contents: write
  deployments: none
  issues: none
  packages: none
  pull-requests: write
  repository-projects: none
  security-events: write
  statuses: none

jobs:
  workflow_variables:
    runs-on: ubuntu-latest
    name: output workflow variables
    outputs:
      build_identifier: "main"
      version_tag: ${{ steps.semver_tag.outputs.created_tag }}
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # pin@v3
      - name: generate semver tag and release
        id: semver_tag
        uses: ministryofjustice/opg-github-actions/.github/actions/semver-tag@v2.5.0
        with:
          prerelease: false
          github_token: ${{ secrets.GITHUB_TOKEN }}

  docker_build_scan_push:
    name: Build, Scan and Push
    needs: ['workflow_variables']
    uses: ./.github/workflows/_docker_build.yml
    with:
      lambda_names: '[{"name": "deputy-reporting-lambda", "path": "lambda_functions/v2"}, {"name": "deputy-reporting-mock-sirius", "path": "mock_sirius"}]'
      tag: ${{ needs.workflow_variables.outputs.build_identifier }}-${{ needs.workflow_variables.outputs.version_tag }}
      build_identifier: ${{ needs.workflow_variables.outputs.build_identifier }}
    secrets:
      aws_access_key_id_actions: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
      aws_secret_access_key_actions: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}

  terraform_plan_apply_account_development:
    name: Terraform Account Development
    needs: ['workflow_variables']
    uses: ./.github/workflows/_terraform.yml
    with:
      terraform_path: 'account'
      workspace: 'development'
    secrets:
      aws_access_key_id_actions: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
      aws_secret_access_key_actions: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}

  terraform_plan_apply_development:
    name: Terraform Environment Development
    needs: ['docker_build_scan_push', 'workflow_variables', 'terraform_plan_apply_account_development']
    uses: ./.github/workflows/_terraform.yml
    with:
      terraform_path: 'environment'
      image_tag: ${{ needs.workflow_variables.outputs.build_identifier }}-${{ needs.workflow_variables.outputs.version_tag }}
      workspace: 'development'
    secrets:
      aws_access_key_id_actions: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
      aws_secret_access_key_actions: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}

  terraform_plan_apply_account_preproduction:
    name: Terraform Account Preproduction
    needs: ['workflow_variables', 'terraform_plan_apply_development']
    uses: ./.github/workflows/_terraform.yml
    with:
      terraform_path: 'account'
      workspace: 'preproduction'
    secrets:
      aws_access_key_id_actions: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
      aws_secret_access_key_actions: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}

  terraform_plan_apply_preproduction:
    name: Terraform Environment Preproduction
    needs: ['workflow_variables', 'terraform_plan_apply_account_preproduction']
    uses: ./.github/workflows/_terraform.yml
    with:
      terraform_path: 'environment'
      image_tag: ${{ needs.workflow_variables.outputs.build_identifier }}-${{ needs.workflow_variables.outputs.version_tag }}
      workspace: 'preproduction'
    secrets:
      aws_access_key_id_actions: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
      aws_secret_access_key_actions: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}

  terraform_plan_apply_account_production:
    name: Terraform Account Production
    needs: ['workflow_variables', 'terraform_plan_apply_preproduction']
    uses: ./.github/workflows/_terraform.yml
    with:
      terraform_path: 'account'
      workspace: 'production'
    secrets:
      aws_access_key_id_actions: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
      aws_secret_access_key_actions: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}

  terraform_plan_apply_production:
    name: Terraform Environment Production
    needs: ['workflow_variables', 'terraform_plan_apply_account_production']
    uses: ./.github/workflows/_terraform.yml
    with:
      terraform_path: 'environment'
      image_tag: ${{ needs.workflow_variables.outputs.build_identifier }}-${{ needs.workflow_variables.outputs.version_tag }}
      workspace: 'production'
    secrets:
      aws_access_key_id_actions: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
      aws_secret_access_key_actions: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}

  create_release:
    name: Create Release
    needs: ['terraform_plan_apply_production', 'workflow_variables']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
