name: Generate scan report

on:
  push:
    branches:
      - "main"
  schedule:
    # Every Tuesday, at 8:40 UTC
    - cron: '40 8 * * 2'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ministryofjustice/opg-repository-scanner@latest
