name: "[Workflow] Path to Live"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  actions: read
  checks: read
  contents: write
  deployments: none
  issues: none
  packages: none
  pull-requests: write
  repository-projects: none
  security-events: write
  statuses: none

jobs:
  workflow_variables:
    runs-on: ubuntu-latest
    name: output workflow variables
    outputs:
      build_identifier: "main"
      version_tag: ${{ steps.semver_tag.outputs.created_tag }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: generate semver tag and release
        id: semver_tag
        uses: ministryofjustice/opg-github-actions/.github/actions/semver-tag@87c9f0610c8b733969292ae15a2d3f6f5637a995 # v2.7.3
        with:
          prerelease: false
          github_token: ${{ secrets.GITHUB_TOKEN }}

  docker_build_scan_push:
    name: Build, Scan and Push
    needs: ['workflow_variables']
    uses: ./.github/workflows/_docker_build.yml
    with:
      tag: ${{ needs.workflow_variables.outputs.version_tag }}
      build_identifier: ${{ needs.workflow_variables.outputs.build_identifier }}

  terraform_plan_apply_account_development:
    name: Terraform Account Development
    needs: ['workflow_variables']
    uses: ./.github/workflows/_terraform.yml
    with:
      terraform_path: 'account'
      workspace: 'development'
      environment: 'development'

  terraform_plan_apply_development:
    name: Terraform Environment Development
    needs: ['docker_build_scan_push', 'workflow_variables', 'terraform_plan_apply_account_development']
    uses: ./.github/workflows/_terraform.yml
    with:
      terraform_path: 'environment'
      image_tag: ${{ needs.workflow_variables.outputs.version_tag }}
      workspace: 'development'
      environment: 'development'
      load_allow_list_private_key: true
    secrets:
      ssh_private_key_allow_list_repository: ${{ secrets.SSH_PRIVATE_KEY_ALLOW_LIST_REPOSITORY }}

  terraform_plan_apply_account_preproduction:
    name: Terraform Account Preproduction
    needs: ['workflow_variables', 'terraform_plan_apply_development']
    uses: ./.github/workflows/_terraform.yml
    with:
      terraform_path: 'account'
      workspace: 'preproduction'
      environment: 'preproduction'

  terraform_plan_apply_preproduction:
    name: Terraform Environment Preproduction
    needs: ['workflow_variables', 'terraform_plan_apply_account_preproduction']
    uses: ./.github/workflows/_terraform.yml
    with:
      terraform_path: 'environment'
      image_tag: ${{ needs.workflow_variables.outputs.version_tag }}
      workspace: 'preproduction'
      environment: 'preproduction'
      load_allow_list_private_key: true
    secrets:
      ssh_private_key_allow_list_repository: ${{ secrets.SSH_PRIVATE_KEY_ALLOW_LIST_REPOSITORY }}

  health_check_preproduction:
    name: Health Check Preproduction
    needs: ['terraform_plan_apply_preproduction']
    uses: ./.github/workflows/_health_check.yml
    with:
      sirius_account_name: 'preproduction'
      environment_prefix: 'pre.'
      digideps_account: 454262938596
      sirius_account: 492687888235
      role: 'sirius-files-sync.preproduction'

  terraform_plan_apply_account_production:
    name: Terraform Account Production
    needs: ['workflow_variables', 'health_check_preproduction']
    uses: ./.github/workflows/_terraform.yml
    with:
      terraform_path: 'account'
      workspace: 'production'
      environment: 'production'

  terraform_plan_apply_production:
    name: Terraform Environment Production
    needs: ['workflow_variables', 'terraform_plan_apply_account_production']
    uses: ./.github/workflows/_terraform.yml
    with:
      terraform_path: 'environment'
      image_tag: ${{ needs.workflow_variables.outputs.version_tag }}
      workspace: 'production'
      environment: 'production'
      load_allow_list_private_key: true
    secrets:
      ssh_private_key_allow_list_repository: ${{ secrets.SSH_PRIVATE_KEY_ALLOW_LIST_REPOSITORY }}

  health_check_production:
    name: Health Check Production
    needs: ['terraform_plan_apply_production']
    uses: ./.github/workflows/_health_check.yml
    with:
      environment_prefix: ''
      sirius_account_name: 'production'
      digideps_account: 515688267891
      sirius_account: 649098267436
      role: 'sirius-files-sync.production02'

  complete_workflow:
    name: Complete Workflow Steps
    needs: ['health_check_production', 'workflow_variables']
    runs-on: ubuntu-latest
    steps:
      - name: workflow complete
        run: echo "Complete Workflow"
